version: '3.2'
services:
  client:
    build: ./client/
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=${NODE_ENV}
      - NODE_PORT=${NODE_PORT}
  cms:
    build: ./products/
    ports:
      - "9090:9090"
  orders:
    build: ./orders/
    ports:
      - "1234:1234"
    environment:
      - RAILS_ENV=${RAILS_ENV}
    depends_on:
      - db
  db:
    image: postgres:11
    volumes:
      - pg_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password

volumes:
  pg_data:
    driver: local
