export const SET_LOADING = "SET_LOADING"

export const SET_LOADED = "SET_LOADED"

export const SET_LOADING_PRODUCTS = "SET_LOADING_PRODUCTS"

export const SET_LOADED_PRODUCTS = "SET_LOADED_PRODUCTS"

export const SET_ERROR = "SET_ERROR"

export const SET_NO_ERROR = "SET_NO_ERROR"

export const TOGGLE_SHOW_CART = "TOGGLE_SHOW_CART"

export const TOGGLE_SHOW_COMPLETE_ORDER = "TOGGLE_SHOW_COMPLETE_ORDER"

export const SET_CREATED_ORDER = "SET_CREATED_ORDER"

export const SET_CREATING_ORDER = "SET_CREATING_ORDER"

export const SET_INFO = "SET_INFO"

export const SET_NO_INFO = "SET_NO_INFO"
